[package]
name="computational_geometry"
edition.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
itertools = "0.14.0"
paste = "*"
rstest = "0.24.0"
rstest_reuse = "*"
tempfile = "3.14.0"