[package]
name = "computational_geometry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

egui_plot = "0.29.0"
indexmap = "2.6.0"
itertools = "0.13.0"
lazy_static = "1.5.0"
rstest = "0.23.0"
unique_id = "0.1.5"
