[workspace]
resolver = "2" 
members = ["computational_geometry", "visualizer"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.76"

[workspace.dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0"