[package]
name = "computational_geometry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

indexmap = "2.6.0"
itertools = "*"
lazy_static = "1.5.0"
rstest = "0.23.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
unique_id = "*"